"use client";

import { useRouter } from "next/navigation";
import { Play, ArrowRight } from "lucide-react";

export default function DemoPage() {
  const router = useRouter();

  const handleRunDemo = (demoKey: string) => {
    router.push(`/results/demo-${demoKey}`);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-10">
      
      {/* Header */}
      <div className="text-center space-y-3">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-md bg-zinc-900 border border-zinc-800 text-[11px] font-mono text-zinc-400">
          <Play className="w-3 h-3 text-zinc-400" />
          <span className="uppercase tracking-wider">Demo Center</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-white">
          Experience TrustLens in 1 Click
        </h1>
        <p className="text-sm text-gray-400 max-w-xl mx-auto">
          Test TrustLens multi-signal verification using pre-configured hackathon demo cases without uploading external files.
        </p>
      </div>

      {/* 3 Demo Preset Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        
        {/* DEMO 1: Authentic */}
        <div
          className="glass-card hover-lift p-6 rounded-3xl border border-emerald-500/30 flex flex-col justify-between space-y-6 bg-gradient-to-b from-[#0F141C] to-emerald-950/10"
        >
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-emerald-400 uppercase tracking-wider">Demo Case 1</span>
              <span className="text-xs px-2.5 py-1 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 font-bold">
                LOWER RISK
              </span>
            </div>

            <div className="space-y-1">
              <h3 className="text-lg font-bold text-white">Authentic Photography</h3>
              <p className="text-xs text-gray-400">Target: DSLR camera photo with valid EXIF headers.</p>
            </div>

            <div className="p-4 rounded-2xl bg-white/5 border border-white/5 space-y-2 text-xs">
              <div className="flex justify-between">
                <span className="text-gray-400">Trust Score:</span>
                <span className="font-bold text-emerald-400">86.5 / 100</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-400">AI Diffusion Risk:</span>
                <span className="font-bold text-emerald-400">12%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-400">EXIF Camera:</span>
                <span className="font-semibold text-gray-200">Canon EOS R5</span>
              </div>
            </div>
          </div>

          <button
            onClick={() => handleRunDemo("authentic")}
            className="press w-full py-3 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-xs font-bold text-white shadow-lg shadow-emerald-600/20 flex items-center justify-center gap-2"
          >
            <span>Run Authentic Demo</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>

        {/* DEMO 2: AI Deepfake */}
        <div
          className="glass-card hover-lift p-6 rounded-3xl border border-rose-500/30 flex flex-col justify-between space-y-6 bg-gradient-to-b from-[#0F141C] to-rose-950/10"
        >
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-rose-400 uppercase tracking-wider">Demo Case 2</span>
              <span className="text-xs px-2.5 py-1 rounded-full bg-rose-500/20 text-rose-300 border border-rose-500/30 font-bold">
                HIGH RISK
              </span>
            </div>

            <div className="space-y-1">
              <h3 className="text-lg font-bold text-white">AI Synthetic Deepfake</h3>
              <p className="text-xs text-gray-400">Target: Generative portrait generated by diffusion model.</p>
            </div>

            <div className="p-4 rounded-2xl bg-white/5 border border-white/5 space-y-2 text-xs">
              <div className="flex justify-between">
                <span className="text-gray-400">Trust Score:</span>
                <span className="font-bold text-rose-400">24.5 / 100</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-400">AI Diffusion Risk:</span>
                <span className="font-bold text-rose-400">92%</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-400">EXIF Software Tag:</span>
                <span className="font-semibold text-rose-300">Midjourney v6</span>
              </div>
            </div>
          </div>

          <button
            onClick={() => handleRunDemo("deepfake")}
            className="press w-full py-3 rounded-xl bg-rose-600 hover:bg-rose-500 text-xs font-bold text-white shadow-lg shadow-rose-600/20 flex items-center justify-center gap-2"
          >
            <span>Run Deepfake Demo</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>

        {/* DEMO 3: Out of Context */}
        <div
          className="glass-card hover-lift p-6 rounded-3xl border border-amber-500/30 flex flex-col justify-between space-y-6 bg-gradient-to-b from-[#0F141C] to-amber-950/10"
        >
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-amber-400 uppercase tracking-wider">Demo Case 3</span>
              <span className="text-xs px-2.5 py-1 rounded-full bg-amber-500/20 text-amber-300 border border-amber-500/30 font-bold">
                VERIFY
              </span>
            </div>

            <div className="space-y-1">
              <h3 className="text-lg font-bold text-white">Out-of-Context Media</h3>
              <p className="text-xs text-gray-400">Target: Real photo shared with misleading headline text.</p>
            </div>

            <div className="p-4 rounded-2xl bg-white/5 border border-white/5 space-y-2 text-xs">
              <div className="flex justify-between">
                <span className="text-gray-400">Trust Score:</span>
                <span className="font-bold text-amber-400">48.0 / 100</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-400">Context Conflict:</span>
                <span className="font-bold text-amber-400">High Mismatch</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-400">Image Structure:</span>
                <span className="font-semibold text-emerald-400">Organic</span>
              </div>
            </div>
          </div>

          <button
            onClick={() => handleRunDemo("out_of_context")}
            className="press w-full py-3 rounded-xl bg-amber-600 hover:bg-amber-500 text-xs font-bold text-white shadow-lg shadow-amber-600/20 flex items-center justify-center gap-2"
          >
            <span>Run Context Demo</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>

      </div>

    </div>
  );
}
